# Generated by Django 4.1.7 on 2023-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmarked', through='market.Wish_list', to='market.userprofile'),
        ),
    ]
