# Generated by Django 4.1.7 on 2023-03-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_products_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, related_name='product', through='market.Product_category', to='market.products'),
        ),
    ]
