# Generated by Django 4.1.7 on 2023-05-07 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_useradmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.client'),
        ),
    ]
