# Generated by Django 4.1.7 on 2023-05-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_userprofile_client_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
