# Generated by Django 4.1.7 on 2023-05-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_delete_useradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='ordered',
            field=models.ManyToManyField(blank=True, default=None, related_name='ordered', through='market.Orders', to='market.userprofile'),
        ),
    ]
