# Generated by Django 4.1.7 on 2023-05-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_orders_products_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('initial_price', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('product_variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product_variants')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='product_variants',
            name='cart_added',
            field=models.ManyToManyField(blank=True, default=None, related_name='cart_added', through='market.Cart', to='market.userprofile'),
        ),
    ]
