# Generated by Django 4.1.7 on 2023-05-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_cart_product_variants_cart_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=45)),
                ('billing_address', models.CharField(max_length=45)),
                ('security_dode', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method_status', models.BooleanField(default=True)),
                ('currency', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Shiping_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=45)),
                ('deadline', models.CharField(max_length=45)),
                ('transportation_cost', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=45)),
                ('availability_status', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wish_list',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.products'),
        ),
        migrations.AlterField(
            model_name='wish_list',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.userprofile'),
        ),
        migrations.CreateModel(
            name='Shiping_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.orders')),
                ('shiping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shiping_method')),
            ],
        ),
        migrations.AddField(
            model_name='shiping_method',
            name='shiping',
            field=models.ManyToManyField(related_name='shiping', through='market.Shiping_Status', to='market.orders'),
        ),
        migrations.CreateModel(
            name='Payment_Stauts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=45)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.orders')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.payment_method')),
            ],
        ),
        migrations.AddField(
            model_name='payment_method',
            name='payment',
            field=models.ManyToManyField(related_name='payment', through='market.Payment_Stauts', to='market.orders'),
        ),
    ]
