# Generated by Django 4.1.7 on 2023-05-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_payment_method_shiping_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_method',
            old_name='security_dode',
            new_name='security_code',
        ),
    ]
